CFD = 'COLLEGE_FOOTBALL_DATA'
SP_PLUS = 'SP_PLUS'
FPI = 'FPI'
ENTROPY = 'ENTROPY'
FIVE_DIMES = 'FIVE_DIMES'
MASSEY = 'MASSEY'

HOME_FIELD_ADVANTAGE = 2.5

CONFERENCES_WITHOUT_DIVISIONS = {'Big 12', 'Sun Belt', 'FBS Independents'}
