TEAMS = {
    'Air Force': {'mascot': 'Falcons', 'abbreviation': 'AFA', 'conference': 'Mountain West', 'division': 'Mountain',
                  'color': '#004a7b', 'alt_color': '#ffffff',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2005.png']},
    'Akron': {'mascot': 'Zips', 'abbreviation': 'AKR', 'conference': 'Mid-American', 'division': 'East',
              'color': '#00285e', 'alt_color': '#84754e',
              'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
                        'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2006.png']},
    'Alabama': {'mascot': 'Crimson Tide', 'abbreviation': 'ALA', 'conference': 'SEC', 'division': 'West',
                'color': '#690014', 'alt_color': '#f1f2f3',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png']},
    'Appalachian State': {'mascot': 'Mountaineers', 'abbreviation': 'APP', 'conference': 'Sun Belt', 'division': None,
                          'color': '#000000', 'alt_color': '#ffcd00',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2026.png']},
    'Arizona': {'mascot': 'Wildcats', 'abbreviation': 'ARIZ', 'conference': 'Pac-12', 'division': 'South',
                'color': '#002449', 'alt_color': '#00205b',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/12.png']},
    'Arizona State': {'mascot': 'Sun Devils', 'abbreviation': 'ASU', 'conference': 'Pac-12', 'division': 'South',
                      'color': '#942139', 'alt_color': '#f1f2f3',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png']},
    'Arkansas': {'mascot': 'Razorbacks', 'abbreviation': 'ARK', 'conference': 'SEC', 'division': 'West',
                 'color': '#9c1831', 'alt_color': '#000000',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png']},
    'Arkansas State': {'mascot': 'Red Wolves', 'abbreviation': 'ARST', 'conference': 'Sun Belt', 'division': None,
                       'color': '#e81018', 'alt_color': '#000000',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2032.png']},
    'Army': {'mascot': 'Black Knights', 'abbreviation': 'ARMY', 'conference': 'FBS Independents', 'division': None,
             'color': '#ce9c00', 'alt_color': '#231f20', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/349.png']},
    'Auburn': {'mascot': 'Tigers', 'abbreviation': 'AUB', 'conference': 'SEC', 'division': 'West', 'color': '#03244d',
               'alt_color': '#f1f2f3', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
                                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2.png']},
    'Ball State': {'mascot': 'Cardinals', 'abbreviation': 'BALL', 'conference': 'Mid-American', 'division': 'West',
                   'color': '#DA0000', 'alt_color': '#ffffff',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2050.png']},
    'Baylor': {'mascot': 'Bears', 'abbreviation': 'BAY', 'conference': 'Big 12', 'division': None, 'color': '#004834',
               'alt_color': '#ffb81c', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
                                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/239.png']},
    'Boise State': {'mascot': 'Broncos', 'abbreviation': 'BSU', 'conference': 'Mountain West', 'division': 'Mountain',
                    'color': '#09347A', 'alt_color': '#d8d9da',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/68.png']},
    'Boston College': {'mascot': 'Eagles', 'abbreviation': 'BC', 'conference': 'ACC', 'division': 'Atlantic',
                       'color': '#88001a', 'alt_color': '#a39161',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/103.png']},
    'Bowling Green': {'mascot': 'Falcons', 'abbreviation': 'BGSU', 'conference': 'Mid-American', 'division': 'East',
                      'color': '#2b1000', 'alt_color': '#492000',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/189.png']},
    'Buffalo': {'mascot': 'Bulls', 'abbreviation': 'BUFF', 'conference': 'Mid-American', 'division': 'East',
                'color': '#041A9B', 'alt_color': '#ebebeb',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2084.png']},
    'BYU': {'mascot': 'Cougars', 'abbreviation': 'BYU', 'conference': 'FBS Independents', 'division': None,
            'color': '#001E4C', 'alt_color': '#ffffff', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
                                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/252.png']},
    'California': {'mascot': 'Golden Bears', 'abbreviation': 'CAL', 'conference': 'Pac-12', 'division': 'North',
                   'color': '#031522', 'alt_color': '#ffc423',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/25.png']},
    'Central Michigan': {'mascot': 'Chippewas', 'abbreviation': 'CMU', 'conference': 'Mid-American', 'division': 'West',
                         'color': '#6a0032', 'alt_color': '#ffffff',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2117.png']},
    'Charlotte': {'mascot': '49ers', 'abbreviation': 'CHAR', 'conference': 'Conference USA', 'division': 'East',
                  'color': '#0C562D', 'alt_color': '#cfab7a',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2429.png']},
    'Cincinnati': {'mascot': 'Bearcats', 'abbreviation': 'CIN', 'conference': 'American Athletic', 'division': 'East',
                   'color': '#000000', 'alt_color': '#717073',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2132.png']},
    'Clemson': {'mascot': 'Tigers', 'abbreviation': 'CLEM', 'conference': 'ACC', 'division': 'Atlantic',
                'color': '#F66733', 'alt_color': '#522d80',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/228.png']},
    'Coastal Carolina': {'mascot': 'Chanticleers', 'abbreviation': 'CCU', 'conference': 'Sun Belt', 'division': None,
                         'color': '#007073', 'alt_color': '#876447',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/324.png']},
    'Colorado': {'mascot': 'Buffaloes', 'abbreviation': 'COLO', 'conference': 'Pac-12', 'division': 'South',
                 'color': '#d1c57e', 'alt_color': '#ffd200',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/38.png']},
    'Colorado State': {'mascot': 'Rams', 'abbreviation': 'CSU', 'conference': 'Mountain West', 'division': 'Mountain',
                       'color': '#004537', 'alt_color': '#ffc425',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/36.png']},
    'Connecticut': {'mascot': 'Huskies', 'abbreviation': 'CONN', 'conference': 'American Athletic', 'division': 'East',
                    'color': '#001d40', 'alt_color': '#f1f2f3',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png']},
    'Duke': {'mascot': 'Blue Devils', 'abbreviation': 'DUKE', 'conference': 'ACC', 'division': 'Coastal',
             'color': '#001A57', 'alt_color': '#f1f2f3', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/150.png']},
    'East Carolina': {'mascot': 'Pirates', 'abbreviation': 'ECU', 'conference': 'American Athletic', 'division': 'East',
                      'color': '#4b1869', 'alt_color': '#f0907b',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/151.png']},
    'Eastern Michigan': {'mascot': 'Eagles', 'abbreviation': 'EMU', 'conference': 'Mid-American', 'division': 'West',
                         'color': '#00331b', 'alt_color': '#f0f0f0',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2199.png']},
    'Florida': {'mascot': 'Gators', 'abbreviation': 'FLA', 'conference': 'SEC', 'division': 'East', 'color': '#0021A5',
                'alt_color': '#0021a5', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/57.png']},
    'Florida Atlantic': {'mascot': 'Owls', 'abbreviation': 'FAU', 'conference': 'Conference USA', 'division': 'East',
                         'color': '#004B85', 'alt_color': '#bb2f4c',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png']},
    'Florida International': {'mascot': 'Golden Panthers', 'abbreviation': 'FIU', 'conference': 'Conference USA',
                              'division': 'East', 'color': '#001538', 'alt_color': '#c5960c',
                              'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
                                        'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2229.png']},
    'Florida State': {'mascot': 'Seminoles', 'abbreviation': 'FSU', 'conference': 'ACC', 'division': 'Atlantic',
                      'color': '#782F40', 'alt_color': '#ceb888',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/52.png']},
    'Fresno State': {'mascot': 'Bulldogs', 'abbreviation': 'FRES', 'conference': 'Mountain West', 'division': 'West',
                     'color': '#c41230', 'alt_color': '#231f20',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/278.png']},
    'Georgia': {'mascot': 'Bulldogs', 'abbreviation': 'UGA', 'conference': 'SEC', 'division': 'East',
                'color': '#CC0000', 'alt_color': '#000000',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/61.png']},
    'Georgia Southern': {'mascot': 'Eagles', 'abbreviation': 'GASO', 'conference': 'Sun Belt', 'division': None,
                         'color': '#003775', 'alt_color': '#f0f0f0',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/290.png']},
    'Georgia State': {'mascot': 'Panthers', 'abbreviation': 'GAST', 'conference': 'Sun Belt', 'division': None,
                      'color': '#1e539a', 'alt_color': '#ebebeb',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2247.png']},
    'Georgia Tech': {'mascot': 'Yellow Jackets', 'abbreviation': 'GT', 'conference': 'ACC', 'division': 'Coastal',
                     'color': '#00223e', 'alt_color': '#002c56',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/59.png']},
    "Hawai'i": {'mascot': 'Rainbow Warriors', 'abbreviation': 'HAW', 'conference': 'Mountain West', 'division': 'West',
                'color': '#003420', 'alt_color': '#ffffff',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/62.png']},
    'Houston': {'mascot': 'Cougars', 'abbreviation': 'HOU', 'conference': 'American Athletic', 'division': 'West',
                'color': '#C90822', 'alt_color': '#231f20',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png']},
    'Illinois': {'mascot': 'Fighting Illini', 'abbreviation': 'ILL', 'conference': 'Big Ten', 'division': 'West',
                 'color': '#f77329', 'alt_color': '#fa6300',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/356.png']},
    'Indiana': {'mascot': 'Hoosiers', 'abbreviation': 'IND', 'conference': 'Big Ten', 'division': 'East',
                'color': '#7D110C', 'alt_color': '#eeedeb',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png']},
    'Iowa': {'mascot': 'Hawkeyes', 'abbreviation': 'IOWA', 'conference': 'Big Ten', 'division': 'West',
             'color': '#000000', 'alt_color': '#ffe100', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2294.png']},
    'Iowa State': {'mascot': 'Cyclones', 'abbreviation': 'ISU', 'conference': 'Big 12', 'division': None,
                   'color': '#660015', 'alt_color': '#830b2c',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/66.png']},
    'Kansas': {'mascot': 'Jayhawks', 'abbreviation': 'KU', 'conference': 'Big 12', 'division': None, 'color': '#0022B4',
               'alt_color': '#e8000d', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
                                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2305.png']},
    'Kansas State': {'mascot': 'Wildcats', 'abbreviation': 'KSU', 'conference': 'Big 12', 'division': None,
                     'color': '#633194', 'alt_color': '#e7d2ad',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png']},
    'Kent State': {'mascot': 'Golden Flashes', 'abbreviation': 'KENT', 'conference': 'Mid-American', 'division': 'East',
                   'color': '#002445', 'alt_color': '#f0b510',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2309.png']},
    'Kentucky': {'mascot': 'Wildcats', 'abbreviation': 'UK', 'conference': 'SEC', 'division': 'East',
                 'color': '#005DAA', 'alt_color': '#ffffff',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/96.png']},
    'Liberty': {'mascot': 'Flames', 'abbreviation': 'LIB', 'conference': 'FBS Independents', 'division': None,
                'color': '#071740', 'alt_color': '#a61f21',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2335.png']},
    'Louisiana': {'mascot': "Ragin' Cajuns", 'abbreviation': 'ULL', 'conference': 'Sun Belt', 'division': None,
                  'color': '#ce2842', 'alt_color': None, 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/309.png']},
    'Louisiana Monroe': {'mascot': 'Warhawks', 'abbreviation': 'ULM', 'conference': 'Sun Belt', 'division': None,
                         'color': '#231F20', 'alt_color': '#b18445',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2433.png']},
    'Louisiana Tech': {'mascot': 'Bulldogs', 'abbreviation': 'LT', 'conference': 'Conference USA', 'division': 'West',
                       'color': '#002d65', 'alt_color': '#d3313a',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2348.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2348.png']},
    'Louisville': {'mascot': 'Cardinals', 'abbreviation': 'LOU', 'conference': 'ACC', 'division': 'Atlantic',
                   'color': '#ad000a', 'alt_color': '#cccccc',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/97.png']},
    'LSU': {'mascot': 'Tigers', 'abbreviation': 'LSU', 'conference': 'SEC', 'division': 'West', 'color': '#22005c',
            'alt_color': '#fdd023', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
                                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/99.png']},
    'Marshall': {'mascot': 'Thundering Herd', 'abbreviation': 'MRSH', 'conference': 'Conference USA',
                 'division': 'East', 'color': '#186329', 'alt_color': '#be854c',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/276.png']},
    'Maryland': {'mascot': 'Terrapins', 'abbreviation': 'MD', 'conference': 'Big Ten', 'division': 'East',
                 'color': '#D5002B', 'alt_color': '#ffcd00',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/120.png']},
    'Memphis': {'mascot': 'Tigers', 'abbreviation': 'MEM', 'conference': 'American Athletic', 'division': 'West',
                'color': '#002447', 'alt_color': '#231f20',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/235.png']},
    'Miami': {'mascot': 'Hurricanes', 'abbreviation': 'MIAMI', 'conference': 'ACC', 'division': 'Coastal',
              'color': '#004325', 'alt_color': '#f0f0f0',
              'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
                        'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png']},
    'Miami (OH)': {'mascot': 'RedHawks', 'abbreviation': 'M-OH', 'conference': 'Mid-American', 'division': 'East',
                   'color': '#a4000c', 'alt_color': '#f0f0f0',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/193.png']},
    'Michigan': {'mascot': 'Wolverines', 'abbreviation': 'MICH', 'conference': 'Big Ten', 'division': 'East',
                 'color': '#00274c', 'alt_color': '#ffcb05',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/130.png']},
    'Michigan State': {'mascot': 'Spartans', 'abbreviation': 'MSU', 'conference': 'Big Ten', 'division': 'East',
                       'color': '#18453B', 'alt_color': '#ffffff',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/127.png']},
    'Middle Tennessee': {'mascot': 'Blue Raiders', 'abbreviation': 'MTSU', 'conference': 'Conference USA',
                         'division': 'East', 'color': '#0079C2', 'alt_color': '#c3c5c8',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2393.png']},
    'Minnesota': {'mascot': 'Golden Gophers', 'abbreviation': 'MINN', 'conference': 'Big Ten', 'division': 'West',
                  'color': '#7F011B', 'alt_color': '#7a0019',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/135.png']},
    'Mississippi State': {'mascot': 'Bulldogs', 'abbreviation': 'MSST', 'conference': 'SEC', 'division': 'West',
                          'color': '#762123', 'alt_color': '#c8c8c8',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/344.png']},
    'Missouri': {'mascot': 'Tigers', 'abbreviation': 'MIZ', 'conference': 'SEC', 'division': 'East', 'color': '#000000',
                 'alt_color': '#000000', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/142.png']},
    'Navy': {'mascot': 'Midshipmen', 'abbreviation': 'NAVY', 'conference': 'American Athletic', 'division': 'West',
             'color': '#131630', 'alt_color': '#b6a77c', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2426.png']},
    'NC State': {'mascot': 'Wolfpack', 'abbreviation': 'NCST', 'conference': 'ACC', 'division': 'Atlantic',
                 'color': '#EF1216', 'alt_color': '#231f20',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/152.png']},
    'Nebraska': {'mascot': 'Cornhuskers', 'abbreviation': 'NEB', 'conference': 'Big Ten', 'division': 'West',
                 'color': '#F20017', 'alt_color': '#f5f1e7',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/158.png']},
    'Nevada': {'mascot': 'Wolf Pack', 'abbreviation': 'NEV', 'conference': 'Mountain West', 'division': 'West',
               'color': '#153E5F', 'alt_color': '#8e9295',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2440.png']},
    'New Mexico': {'mascot': 'Lobos', 'abbreviation': 'UNM', 'conference': 'Mountain West', 'division': 'Mountain',
                   'color': '#000000', 'alt_color': '#231f20',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/167.png']},
    'New Mexico State': {'mascot': 'Aggies', 'abbreviation': 'NMSU', 'conference': 'FBS Independents', 'division': None,
                         'color': '#891216', 'alt_color': '#000000',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/166.png']},
    'North Carolina': {'mascot': 'Tar Heels', 'abbreviation': 'UNC', 'conference': 'ACC', 'division': 'Coastal',
                       'color': '#99bfe5', 'alt_color': '#13294b',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/153.png']},
    'Northern Illinois': {'mascot': 'Huskies', 'abbreviation': 'NIU', 'conference': 'Mid-American', 'division': 'West',
                          'color': '#F1122C', 'alt_color': '#cc0000',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2459.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2459.png']},
    'North Texas': {'mascot': 'Mean Green', 'abbreviation': 'UNT', 'conference': 'Conference USA', 'division': 'West',
                    'color': '#00853D', 'alt_color': '#000000',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/249.png']},
    'Northwestern': {'mascot': 'Wildcats', 'abbreviation': 'NW', 'conference': 'Big Ten', 'division': 'West',
                     'color': '#372286', 'alt_color': '#d6cac1',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/77.png']},
    'Notre Dame': {'mascot': 'Fighting Irish', 'abbreviation': 'ND', 'conference': 'FBS Independents', 'division': None,
                   'color': '#00122b', 'alt_color': '#ae9142',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/87.png']},
    'Ohio': {'mascot': 'Bobcats', 'abbreviation': 'OHIO', 'conference': 'Mid-American', 'division': 'East',
             'color': '#295A29', 'alt_color': '#e4bb85', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/195.png']},
    'Ohio State': {'mascot': 'Buckeyes', 'abbreviation': 'OSU', 'conference': 'Big Ten', 'division': 'East',
                   'color': '#DE3121', 'alt_color': '#666666',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/194.png']},
    'Oklahoma': {'mascot': 'Sooners', 'abbreviation': 'OKLA', 'conference': 'Big 12', 'division': None,
                 'color': '#7b0000', 'alt_color': '#cccccc',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/201.png']},
    'Oklahoma State': {'mascot': 'Cowboys', 'abbreviation': 'OKST', 'conference': 'Big 12', 'division': None,
                       'color': '#FF6500', 'alt_color': '#ff9900',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/197.png']},
    'Old Dominion': {'mascot': 'Monarchs', 'abbreviation': 'ODU', 'conference': 'Conference USA', 'division': 'East',
                     'color': '#00507d', 'alt_color': '#a1d2f1',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/295.png']},
    'Ole Miss': {'mascot': 'Rebels', 'abbreviation': 'MISS', 'conference': 'SEC', 'division': 'West',
                 'color': '#001148', 'alt_color': '#00205b',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/145.png']},
    'Oregon': {'mascot': 'Ducks', 'abbreviation': 'ORE', 'conference': 'Pac-12', 'division': 'North',
               'color': '#044520', 'alt_color': '#fee123',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2483.png']},
    'Oregon State': {'mascot': 'Beavers', 'abbreviation': 'ORST', 'conference': 'Pac-12', 'division': 'North',
                     'color': '#c34500', 'alt_color': '#dea076',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/204.png']},
    'Penn State': {'mascot': 'Nittany Lions', 'abbreviation': 'PSU', 'conference': 'Big Ten', 'division': 'East',
                   'color': '#00265D', 'alt_color': '#002e5c',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png']},
    'Pittsburgh': {'mascot': 'Panthers', 'abbreviation': 'PITT', 'conference': 'ACC', 'division': 'Coastal',
                   'color': '#003263', 'alt_color': '#231f20',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/221.png']},
    'Purdue': {'mascot': 'Boilermakers', 'abbreviation': 'PUR', 'conference': 'Big Ten', 'division': 'West',
               'color': '#B89D29', 'alt_color': '#a4a9ad',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2509.png']},
    'Rice': {'mascot': 'Owls', 'abbreviation': 'RICE', 'conference': 'Conference USA', 'division': 'West',
             'color': '#003D7D', 'alt_color': '#d1d5d8', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/242.png']},
    'Rutgers': {'mascot': 'Scarlet Knights', 'abbreviation': 'RUTG', 'conference': 'Big Ten', 'division': 'East',
                'color': '#d21034', 'alt_color': '#ffffff',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/164.png']},
    'San Diego State': {'mascot': 'Aztecs', 'abbreviation': 'SDSU', 'conference': 'Mountain West', 'division': 'West',
                        'color': '#BF2C37', 'alt_color': '#a8996e',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png']},
    'San José State': {'mascot': 'Spartans', 'abbreviation': 'SJSU', 'conference': 'Mountain West', 'division': 'West',
                       'color': '#005893', 'alt_color': '#fdba31',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/23.png']},
    'SMU': {'mascot': 'Mustangs', 'abbreviation': 'SMU', 'conference': 'American Athletic', 'division': 'West',
            'color': '#E32F38', 'alt_color': '#ecdcb9', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
                                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2567.png']},
    'South Alabama': {'mascot': 'Jaguars', 'abbreviation': 'USA', 'conference': 'Sun Belt', 'division': None,
                      'color': '#003E7E', 'alt_color': None,
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/6.png']},
    'South Carolina': {'mascot': 'Gamecocks', 'abbreviation': 'SC', 'conference': 'SEC', 'division': 'East',
                       'color': '#670010', 'alt_color': '#000000',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2579.png']},
    'Southern Mississippi': {'mascot': 'Golden Eagles', 'abbreviation': 'USM', 'conference': 'Conference USA',
                             'division': 'West', 'color': '#FFAA3C', 'alt_color': '#ffc423',
                             'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
                                       'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2572.png']},
    'South Florida': {'mascot': 'Bulls', 'abbreviation': 'USF', 'conference': 'American Athletic', 'division': 'East',
                      'color': '#004A36', 'alt_color': '#231f20',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/58.png']},
    'Stanford': {'mascot': 'Cardinal', 'abbreviation': 'STAN', 'conference': 'Pac-12', 'division': 'North',
                 'color': '#A80532', 'alt_color': '#ffffff',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/24.png']},
    'Syracuse': {'mascot': 'Orange', 'abbreviation': 'SYR', 'conference': 'ACC', 'division': 'Atlantic',
                 'color': '#F37321', 'alt_color': '#0d1d37',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/183.png']},
    'TCU': {'mascot': 'Horned Frogs', 'abbreviation': 'TCU', 'conference': 'Big 12', 'division': None,
            'color': '#3C377D', 'alt_color': '#f1f2f3', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
                                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2628.png']},
    'Temple': {'mascot': 'Owls', 'abbreviation': 'TEM', 'conference': 'American Athletic', 'division': 'East',
               'color': '#A80532', 'alt_color': '#a7a9ac',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/218.png']},
    'Tennessee': {'mascot': 'Volunteers', 'abbreviation': 'TENN', 'conference': 'SEC', 'division': 'East',
                  'color': '#EE9627', 'alt_color': '#ffffff',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png']},
    'Texas': {'mascot': 'Longhorns', 'abbreviation': 'TEX', 'conference': 'Big 12', 'division': None,
              'color': '#EE7524', 'alt_color': '#f0f0f0', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
                                                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png']},
    'Texas A&M': {'mascot': 'Aggies', 'abbreviation': 'TA&M', 'conference': 'SEC', 'division': 'West',
                  'color': '#5C0025', 'alt_color': '#ffffff',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/245.png']},
    'Texas State': {'mascot': 'Bobcats', 'abbreviation': 'TXST', 'conference': 'Sun Belt', 'division': None,
                    'color': '#4e1719', 'alt_color': '#b4975a',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/326.png']},
    'Texas Tech': {'mascot': 'Red Raiders', 'abbreviation': 'TTU', 'conference': 'Big 12', 'division': None,
                   'color': '#C80025', 'alt_color': '#231f20',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2641.png']},
    'Toledo': {'mascot': 'Rockets', 'abbreviation': 'TOL', 'conference': 'Mid-American', 'division': 'West',
               'color': '#00488F', 'alt_color': '#ffd51d',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2649.png']},
    'Troy': {'mascot': 'Trojans', 'abbreviation': 'TROY', 'conference': 'Sun Belt', 'division': None,
             'color': '#AE0210', 'alt_color': '#88898c', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2653.png']},
    'Tulane': {'mascot': 'Green Wave', 'abbreviation': 'TULN', 'conference': 'American Athletic', 'division': 'West',
               'color': '#005837', 'alt_color': '#3baf29',
               'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
                         'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2655.png']},
    'Tulsa': {'mascot': 'Golden Hurricane', 'abbreviation': 'TLSA', 'conference': 'American Athletic',
              'division': 'West', 'color': '#004371', 'alt_color': '#ee3b33',
              'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
                        'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/202.png']},
    'UAB': {'mascot': 'Blazers', 'abbreviation': 'UAB', 'conference': 'Conference USA', 'division': 'West',
            'color': '#003b28', 'alt_color': '#ffc845', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
                                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/5.png']},
    'UCF': {'mascot': 'Knights', 'abbreviation': 'UCF', 'conference': 'American Athletic', 'division': 'East',
            'color': '#000000', 'alt_color': '#231f20', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
                                                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2116.png']},
    'UCLA': {'mascot': 'Bruins', 'abbreviation': 'UCLA', 'conference': 'Pac-12', 'division': 'South',
             'color': '#005C8E', 'alt_color': '#ffc72c', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png']},
    'UMass': {'mascot': 'Minutemen', 'abbreviation': 'UMASS', 'conference': 'FBS Independents', 'division': None,
              'color': '#880007', 'alt_color': None, 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
                                                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/113.png']},
    'UNLV': {'mascot': 'Rebels', 'abbreviation': 'UNLV', 'conference': 'Mountain West', 'division': 'West',
             'color': '#000000', 'alt_color': '#c2c4c6', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2439.png']},
    'USC': {'mascot': 'Trojans', 'abbreviation': 'USC', 'conference': 'Pac-12', 'division': 'South', 'color': '#AE2531',
            'alt_color': '#ffc72c', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
                                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/30.png']},
    'Utah': {'mascot': 'Utes', 'abbreviation': 'UTAH', 'conference': 'Pac-12', 'division': 'South', 'color': '#890012',
             'alt_color': '#7e8083', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
                                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/254.png']},
    'Utah State': {'mascot': 'Aggies', 'abbreviation': 'USU', 'conference': 'Mountain West', 'division': 'Mountain',
                   'color': '#003263', 'alt_color': '#949ca1',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/328.png']},
    'UTEP': {'mascot': 'Miners', 'abbreviation': 'UTEP', 'conference': 'Conference USA', 'division': 'West',
             'color': '#002843', 'alt_color': '#ff6f12', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
                                                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2638.png']},
    'UT San Antonio': {'mascot': 'Roadrunners', 'abbreviation': 'UTSA', 'conference': 'Conference USA',
                       'division': 'West', 'color': '#002A5C', 'alt_color': '#f47321',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2636.png']},
    'Vanderbilt': {'mascot': 'Commodores', 'abbreviation': 'VAN', 'conference': 'SEC', 'division': 'East',
                   'color': '#000000', 'alt_color': '#231f20',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/238.png']},
    'Virginia': {'mascot': 'Cavaliers', 'abbreviation': 'UVA', 'conference': 'ACC', 'division': 'Coastal',
                 'color': '#00204e', 'alt_color': '#002d62',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/258.png']},
    'Virginia Tech': {'mascot': 'Hokies', 'abbreviation': 'VT', 'conference': 'ACC', 'division': 'Coastal',
                      'color': '#74232D', 'alt_color': '#c2c1ba',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/259.png']},
    'Wake Forest': {'mascot': 'Demon Deacons', 'abbreviation': 'WAKE', 'conference': 'ACC', 'division': 'Atlantic',
                    'color': '#9E7E38', 'alt_color': '#000000',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/154.png']},
    'Washington': {'mascot': 'Huskies', 'abbreviation': 'WASH', 'conference': 'Pac-12', 'division': 'North',
                   'color': '#2B2F64', 'alt_color': '#e8e3d3',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/264.png']},
    'Washington State': {'mascot': 'Cougars', 'abbreviation': 'WSU', 'conference': 'Pac-12', 'division': 'North',
                         'color': '#94022a', 'alt_color': '#6a747c',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/265.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/265.png']},
    'Western Kentucky': {'mascot': 'Hilltoppers', 'abbreviation': 'WKU', 'conference': 'Conference USA',
                         'division': 'East', 'color': '#F32026', 'alt_color': '#b3b5b8',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/98.png']},
    'Western Michigan': {'mascot': 'Broncos', 'abbreviation': 'WMU', 'conference': 'Mid-American', 'division': 'West',
                         'color': '#B59966', 'alt_color': '#bfa979',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2711.png']},
    'West Virginia': {'mascot': 'Mountaineers', 'abbreviation': 'WVU', 'conference': 'Big 12', 'division': None,
                      'color': '#FFC600', 'alt_color': '#eaaa00',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/277.png']},
    'Wisconsin': {'mascot': 'Badgers', 'abbreviation': 'WIS', 'conference': 'Big Ten', 'division': 'West',
                  'color': '#A00001', 'alt_color': '#f7f7f7',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/275.png']},
    'Wyoming': {'mascot': 'Cowboys', 'abbreviation': 'WYO', 'conference': 'Mountain West', 'division': 'Mountain',
                'color': '#533B22', 'alt_color': '#ffffff',
                'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2751.png']}}
