TEAMS = {'Air Force': {'school': 'Air Force', 'mascot': 'Falcons', 'abbreviation': 'AFA', 'conference': 'Mountain West',
                       'division': 'Mountain', 'color': '#004a7b', 'alt_color': '#ffffff',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2005.png']},
         'Akron': {'school': 'Akron', 'mascot': 'Zips', 'abbreviation': 'AKR', 'conference': 'Mid-American',
                   'division': 'East', 'color': '#00285e', 'alt_color': '#84754e',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2006.png']},
         'Alabama': {'school': 'Alabama', 'mascot': 'Crimson Tide', 'abbreviation': 'ALA', 'conference': 'SEC',
                     'division': 'West', 'color': '#690014', 'alt_color': '#f1f2f3',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png']},
         'Arizona': {'school': 'Arizona', 'mascot': 'Wildcats', 'abbreviation': 'ARIZ', 'conference': 'Pac-12',
                     'division': 'South', 'color': '#002449', 'alt_color': '#00205b',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/12.png']},
         'Arizona State': {'school': 'Arizona State', 'mascot': 'Sun Devils', 'abbreviation': 'ASU',
                           'conference': 'Pac-12', 'division': 'South', 'color': '#942139', 'alt_color': '#f1f2f3',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png']},
         'Arkansas': {'school': 'Arkansas', 'mascot': 'Razorbacks', 'abbreviation': 'ARK', 'conference': 'SEC',
                      'division': 'West', 'color': '#9c1831', 'alt_color': '#000000',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png']},
         'Arkansas State': {'school': 'Arkansas State', 'mascot': 'Red Wolves', 'abbreviation': 'ARST',
                            'conference': 'Sun Belt', 'division': None, 'color': '#e81018', 'alt_color': '#000000',
                            'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
                                      'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2032.png']},
         'Army': {'school': 'Army', 'mascot': 'Black Knights', 'abbreviation': 'ARMY', 'conference': 'FBS Independents',
                  'division': None, 'color': '#ce9c00', 'alt_color': '#231f20',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/349.png']},
         'Auburn': {'school': 'Auburn', 'mascot': 'Tigers', 'abbreviation': 'AUB', 'conference': 'SEC',
                    'division': 'West', 'color': '#03244d', 'alt_color': '#f1f2f3',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2.png']},
         'Ball State': {'school': 'Ball State', 'mascot': 'Cardinals', 'abbreviation': 'BALL',
                        'conference': 'Mid-American', 'division': 'West', 'color': '#DA0000', 'alt_color': '#ffffff',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2050.png']},
         'Baylor': {'school': 'Baylor', 'mascot': 'Bears', 'abbreviation': 'BAY', 'conference': 'Big 12',
                    'division': None, 'color': '#004834', 'alt_color': '#ffb81c',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/239.png']},
         'Boise State': {'school': 'Boise State', 'mascot': 'Broncos', 'abbreviation': 'BSU',
                         'conference': 'Mountain West', 'division': 'Mountain', 'color': '#09347A',
                         'alt_color': '#d8d9da', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
                                                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/68.png']},
         'Boston College': {'school': 'Boston College', 'mascot': 'Eagles', 'abbreviation': 'BC', 'conference': 'ACC',
                            'division': 'Atlantic', 'color': '#88001a', 'alt_color': '#a39161',
                            'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
                                      'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/103.png']},
         'Bowling Green': {'school': 'Bowling Green', 'mascot': 'Falcons', 'abbreviation': 'BGSU',
                           'conference': 'Mid-American', 'division': 'East', 'color': '#2b1000', 'alt_color': '#492000',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/189.png']},
         'Buffalo': {'school': 'Buffalo', 'mascot': 'Bulls', 'abbreviation': 'BUFF', 'conference': 'Mid-American',
                     'division': 'East', 'color': '#041A9B', 'alt_color': '#ebebeb',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2084.png']},
         'BYU': {'school': 'BYU', 'mascot': 'Cougars', 'abbreviation': 'BYU', 'conference': 'FBS Independents',
                 'division': None, 'color': '#001E4C', 'alt_color': '#ffffff',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/252.png']},
         'Charlotte': {'school': 'Charlotte', 'mascot': '49ers', 'abbreviation': 'CHAR', 'conference': 'Conference USA',
                       'division': 'East', 'color': '#0C562D', 'alt_color': '#cfab7a',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2429.png']},
         'Cincinnati': {'school': 'Cincinnati', 'mascot': 'Bearcats', 'abbreviation': 'CIN',
                        'conference': 'American Athletic', 'division': 'East', 'color': '#000000',
                        'alt_color': '#717073', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
                                                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2132.png']},
         'Clemson': {'school': 'Clemson', 'mascot': 'Tigers', 'abbreviation': 'CLEM', 'conference': 'ACC',
                     'division': 'Atlantic', 'color': '#F66733', 'alt_color': '#522d80',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/228.png']},
         'Colorado': {'school': 'Colorado', 'mascot': 'Buffaloes', 'abbreviation': 'COLO', 'conference': 'Pac-12',
                      'division': 'South', 'color': '#d1c57e', 'alt_color': '#ffd200',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/38.png']},
         'Colorado State': {'school': 'Colorado State', 'mascot': 'Rams', 'abbreviation': 'CSU',
                            'conference': 'Mountain West', 'division': 'Mountain', 'color': '#004537',
                            'alt_color': '#ffc425', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
                                                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/36.png']},
         'Duke': {'school': 'Duke', 'mascot': 'Blue Devils', 'abbreviation': 'DUKE', 'conference': 'ACC',
                  'division': 'Coastal', 'color': '#001A57', 'alt_color': '#f1f2f3',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/150.png']},
         'East Carolina': {'school': 'East Carolina', 'mascot': 'Pirates', 'abbreviation': 'ECU',
                           'conference': 'American Athletic', 'division': 'East', 'color': '#4b1869',
                           'alt_color': '#f0907b', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
                                                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/151.png']},
         'Florida': {'school': 'Florida', 'mascot': 'Gators', 'abbreviation': 'FLA', 'conference': 'SEC',
                     'division': 'East', 'color': '#0021A5', 'alt_color': '#0021a5',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/57.png']},
         'Florida State': {'school': 'Florida State', 'mascot': 'Seminoles', 'abbreviation': 'FSU', 'conference': 'ACC',
                           'division': 'Atlantic', 'color': '#782F40', 'alt_color': '#ceb888',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/52.png']},
         'Fresno State': {'school': 'Fresno State', 'mascot': 'Bulldogs', 'abbreviation': 'FRES',
                          'conference': 'Mountain West', 'division': 'West', 'color': '#c41230', 'alt_color': '#231f20',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/278.png']},
         'Georgia': {'school': 'Georgia', 'mascot': 'Bulldogs', 'abbreviation': 'UGA', 'conference': 'SEC',
                     'division': 'East', 'color': '#CC0000', 'alt_color': '#000000',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/61.png']},
         'Georgia State': {'school': 'Georgia State', 'mascot': 'Panthers', 'abbreviation': 'GAST',
                           'conference': 'Sun Belt', 'division': None, 'color': '#1e539a', 'alt_color': '#ebebeb',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2247.png']},
         'Georgia Tech': {'school': 'Georgia Tech', 'mascot': 'Yellow Jackets', 'abbreviation': 'GT',
                          'conference': 'ACC', 'division': 'Coastal', 'color': '#00223e', 'alt_color': '#002c56',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/59.png']},
         "Hawai'i": {'school': "Hawai'i", 'mascot': 'Rainbow Warriors', 'abbreviation': 'HAW',
                     'conference': 'Mountain West', 'division': 'West', 'color': '#003420', 'alt_color': '#ffffff',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/62.png']},
         'Houston': {'school': 'Houston', 'mascot': 'Cougars', 'abbreviation': 'HOU', 'conference': 'American Athletic',
                     'division': 'West', 'color': '#C90822', 'alt_color': '#231f20',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png']},
         'Illinois': {'school': 'Illinois', 'mascot': 'Fighting Illini', 'abbreviation': 'ILL', 'conference': 'Big Ten',
                      'division': 'West', 'color': '#f77329', 'alt_color': '#fa6300',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/356.png']},
         'Indiana': {'school': 'Indiana', 'mascot': 'Hoosiers', 'abbreviation': 'IND', 'conference': 'Big Ten',
                     'division': 'East', 'color': '#7D110C', 'alt_color': '#eeedeb',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png']},
         'Iowa': {'school': 'Iowa', 'mascot': 'Hawkeyes', 'abbreviation': 'IOWA', 'conference': 'Big Ten',
                  'division': 'West', 'color': '#000000', 'alt_color': '#ffe100',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2294.png']},
         'Iowa State': {'school': 'Iowa State', 'mascot': 'Cyclones', 'abbreviation': 'ISU', 'conference': 'Big 12',
                        'division': None, 'color': '#660015', 'alt_color': '#830b2c',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/66.png']},
         'Kansas': {'school': 'Kansas', 'mascot': 'Jayhawks', 'abbreviation': 'KU', 'conference': 'Big 12',
                    'division': None, 'color': '#0022B4', 'alt_color': '#e8000d',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2305.png']},
         'Kansas State': {'school': 'Kansas State', 'mascot': 'Wildcats', 'abbreviation': 'KSU', 'conference': 'Big 12',
                          'division': None, 'color': '#633194', 'alt_color': '#e7d2ad',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png']},
         'Kent State': {'school': 'Kent State', 'mascot': 'Golden Flashes', 'abbreviation': 'KENT',
                        'conference': 'Mid-American', 'division': 'East', 'color': '#002445', 'alt_color': '#f0b510',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2309.png']},
         'Kentucky': {'school': 'Kentucky', 'mascot': 'Wildcats', 'abbreviation': 'UK', 'conference': 'SEC',
                      'division': 'East', 'color': '#005DAA', 'alt_color': '#ffffff',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/96.png']},
         'Liberty': {'school': 'Liberty', 'mascot': 'Flames', 'abbreviation': 'LIB', 'conference': None,
                     'division': None, 'color': '#071740', 'alt_color': '#a61f21',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2335.png']},
         'Louisiana': {'school': 'Louisiana', 'mascot': "Ragin' Cajuns", 'abbreviation': 'ULL',
                       'conference': 'Sun Belt', 'division': None, 'color': '#ce2842', 'alt_color': None,
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/309.png']},
         'Louisville': {'school': 'Louisville', 'mascot': 'Cardinals', 'abbreviation': 'LOU', 'conference': 'ACC',
                        'division': 'Atlantic', 'color': '#ad000a', 'alt_color': '#cccccc',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/97.png']},
         'LSU': {'school': 'LSU', 'mascot': 'Tigers', 'abbreviation': 'LSU', 'conference': 'SEC', 'division': 'West',
                 'color': '#22005c', 'alt_color': '#fdd023',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/99.png']},
         'Marshall': {'school': 'Marshall', 'mascot': 'Thundering Herd', 'abbreviation': 'MRSH',
                      'conference': 'Conference USA', 'division': 'East', 'color': '#186329', 'alt_color': '#be854c',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/276.png']},
         'Maryland': {'school': 'Maryland', 'mascot': 'Terrapins', 'abbreviation': 'MD', 'conference': 'Big Ten',
                      'division': 'East', 'color': '#D5002B', 'alt_color': '#ffcd00',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/120.png']},
         'Memphis': {'school': 'Memphis', 'mascot': 'Tigers', 'abbreviation': 'MEM', 'conference': 'American Athletic',
                     'division': 'West', 'color': '#002447', 'alt_color': '#231f20',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/235.png']},
         'Miami': {'school': 'Miami', 'mascot': 'Hurricanes', 'abbreviation': 'MIAMI', 'conference': 'ACC',
                   'division': 'Coastal', 'color': '#004325', 'alt_color': '#f0f0f0',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png']},
         'Miami (OH)': {'school': 'Miami (OH)', 'mascot': 'RedHawks', 'abbreviation': 'M-OH',
                        'conference': 'Mid-American', 'division': 'East', 'color': '#a4000c', 'alt_color': '#f0f0f0',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/193.png']},
         'Michigan': {'school': 'Michigan', 'mascot': 'Wolverines', 'abbreviation': 'MICH', 'conference': 'Big Ten',
                      'division': 'East', 'color': '#00274c', 'alt_color': '#ffcb05',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/130.png']},
         'Minnesota': {'school': 'Minnesota', 'mascot': 'Golden Gophers', 'abbreviation': 'MINN',
                       'conference': 'Big Ten', 'division': 'West', 'color': '#7F011B', 'alt_color': '#7a0019',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/135.png']},
         'Missouri': {'school': 'Missouri', 'mascot': 'Tigers', 'abbreviation': 'MIZ', 'conference': 'SEC',
                      'division': 'East', 'color': '#000000', 'alt_color': '#000000',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/142.png']},
         'Navy': {'school': 'Navy', 'mascot': 'Midshipmen', 'abbreviation': 'NAVY', 'conference': 'American Athletic',
                  'division': 'West', 'color': '#131630', 'alt_color': '#b6a77c',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2426.png']},
         'NC State': {'school': 'NC State', 'mascot': 'Wolfpack', 'abbreviation': 'NCST', 'conference': 'ACC',
                      'division': 'Atlantic', 'color': '#EF1216', 'alt_color': '#231f20',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/152.png']},
         'Nebraska': {'school': 'Nebraska', 'mascot': 'Cornhuskers', 'abbreviation': 'NEB', 'conference': 'Big Ten',
                      'division': 'West', 'color': '#F20017', 'alt_color': '#f5f1e7',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/158.png']},
         'Nevada': {'school': 'Nevada', 'mascot': 'Wolf Pack', 'abbreviation': 'NEV', 'conference': 'Mountain West',
                    'division': 'West', 'color': '#153E5F', 'alt_color': '#8e9295',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2440.png']},
         'New Mexico': {'school': 'New Mexico', 'mascot': 'Lobos', 'abbreviation': 'UNM', 'conference': 'Mountain West',
                        'division': 'Mountain', 'color': '#000000', 'alt_color': '#231f20',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/167.png']},
         'North Carolina': {'school': 'North Carolina', 'mascot': 'Tar Heels', 'abbreviation': 'UNC',
                            'conference': 'ACC', 'division': 'Coastal', 'color': '#99bfe5', 'alt_color': '#13294b',
                            'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
                                      'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/153.png']},
         'North Texas': {'school': 'North Texas', 'mascot': 'Mean Green', 'abbreviation': 'UNT',
                         'conference': 'Conference USA', 'division': 'West', 'color': '#00853D', 'alt_color': '#000000',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/249.png']},
         'Northwestern': {'school': 'Northwestern', 'mascot': 'Wildcats', 'abbreviation': 'NW', 'conference': 'Big Ten',
                          'division': 'West', 'color': '#372286', 'alt_color': '#d6cac1',
                          'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
                                    'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/77.png']},
         'Notre Dame': {'school': 'Notre Dame', 'mascot': 'Fighting Irish', 'abbreviation': 'ND',
                        'conference': 'FBS Independents', 'division': None, 'color': '#00122b', 'alt_color': '#ae9142',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/87.png']},
         'Ohio': {'school': 'Ohio', 'mascot': 'Bobcats', 'abbreviation': 'OHIO', 'conference': 'Mid-American',
                  'division': 'East', 'color': '#295A29', 'alt_color': '#e4bb85',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/195.png']},
         'Ohio State': {'school': 'Ohio State', 'mascot': 'Buckeyes', 'abbreviation': 'OSU', 'conference': 'Big Ten',
                        'division': 'East', 'color': '#DE3121', 'alt_color': '#666666',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/194.png']},
         'Oklahoma': {'school': 'Oklahoma', 'mascot': 'Sooners', 'abbreviation': 'OKLA', 'conference': 'Big 12',
                      'division': None, 'color': '#7b0000', 'alt_color': '#cccccc',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/201.png']},
         'Oklahoma State': {'school': 'Oklahoma State', 'mascot': 'Cowboys', 'abbreviation': 'OKST',
                            'conference': 'Big 12', 'division': None, 'color': '#FF6500', 'alt_color': '#ff9900',
                            'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
                                      'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/197.png']},
         'Old Dominion': {'school': 'Old Dominion', 'mascot': 'Monarchs', 'abbreviation': 'ODU',
                          'conference': 'Conference USA', 'division': 'East', 'color': '#00507d',
                          'alt_color': '#a1d2f1', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
                                                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/295.png']},
         'Ole Miss': {'school': 'Ole Miss', 'mascot': 'Rebels', 'abbreviation': 'MISS', 'conference': 'SEC',
                      'division': 'West', 'color': '#001148', 'alt_color': '#00205b',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/145.png']},
         'Oregon': {'school': 'Oregon', 'mascot': 'Ducks', 'abbreviation': 'ORE', 'conference': 'Pac-12',
                    'division': 'North', 'color': '#044520', 'alt_color': '#fee123',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2483.png']},
         'Penn State': {'school': 'Penn State', 'mascot': 'Nittany Lions', 'abbreviation': 'PSU',
                        'conference': 'Big Ten', 'division': 'East', 'color': '#00265D', 'alt_color': '#002e5c',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png']},
         'Purdue': {'school': 'Purdue', 'mascot': 'Boilermakers', 'abbreviation': 'PUR', 'conference': 'Big Ten',
                    'division': 'West', 'color': '#B89D29', 'alt_color': '#a4a9ad',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2509.png']},
         'Rice': {'school': 'Rice', 'mascot': 'Owls', 'abbreviation': 'RICE', 'conference': 'Conference USA',
                  'division': 'West', 'color': '#003D7D', 'alt_color': '#d1d5d8',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/242.png']},
         'Rutgers': {'school': 'Rutgers', 'mascot': 'Scarlet Knights', 'abbreviation': 'RUTG', 'conference': 'Big Ten',
                     'division': 'East', 'color': '#d21034', 'alt_color': '#ffffff',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/164.png']},
         'San Diego State': {'school': 'San Diego State', 'mascot': 'Aztecs', 'abbreviation': 'SDSU',
                             'conference': 'Mountain West', 'division': 'West', 'color': '#BF2C37',
                             'alt_color': '#a8996e', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
                                                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png']},
         'SMU': {'school': 'SMU', 'mascot': 'Mustangs', 'abbreviation': 'SMU', 'conference': 'American Athletic',
                 'division': 'West', 'color': '#E32F38', 'alt_color': '#ecdcb9',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2567.png']},
         'South Alabama': {'school': 'South Alabama', 'mascot': 'Jaguars', 'abbreviation': 'USA',
                           'conference': 'Sun Belt', 'division': None, 'color': '#003E7E', 'alt_color': None,
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/6.png']},
         'Stanford': {'school': 'Stanford', 'mascot': 'Cardinal', 'abbreviation': 'STAN', 'conference': 'Pac-12',
                      'division': 'North', 'color': '#A80532', 'alt_color': '#ffffff',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/24.png']},
         'Syracuse': {'school': 'Syracuse', 'mascot': 'Orange', 'abbreviation': 'SYR', 'conference': 'ACC',
                      'division': 'Atlantic', 'color': '#F37321', 'alt_color': '#0d1d37',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/183.png']},
         'TCU': {'school': 'TCU', 'mascot': 'Horned Frogs', 'abbreviation': 'TCU', 'conference': 'Big 12',
                 'division': None, 'color': '#3C377D', 'alt_color': '#f1f2f3',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2628.png']},
         'Temple': {'school': 'Temple', 'mascot': 'Owls', 'abbreviation': 'TEM', 'conference': 'American Athletic',
                    'division': 'East', 'color': '#A80532', 'alt_color': '#a7a9ac',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/218.png']},
         'Tennessee': {'school': 'Tennessee', 'mascot': 'Volunteers', 'abbreviation': 'TENN', 'conference': 'SEC',
                       'division': 'East', 'color': '#EE9627', 'alt_color': '#ffffff',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png']},
         'Texas': {'school': 'Texas', 'mascot': 'Longhorns', 'abbreviation': 'TEX', 'conference': 'Big 12',
                   'division': None, 'color': '#EE7524', 'alt_color': '#f0f0f0',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png']},
         'Texas A&M': {'school': 'Texas A&M', 'mascot': 'Aggies', 'abbreviation': 'TA&M', 'conference': 'SEC',
                       'division': 'West', 'color': '#5C0025', 'alt_color': '#ffffff',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/245.png']},
         'Texas State': {'school': 'Texas State', 'mascot': 'Bobcats', 'abbreviation': 'TXST', 'conference': 'Sun Belt',
                         'division': None, 'color': '#4e1719', 'alt_color': '#b4975a',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/326.png']},
         'Texas Tech': {'school': 'Texas Tech', 'mascot': 'Red Raiders', 'abbreviation': 'TTU', 'conference': 'Big 12',
                        'division': None, 'color': '#C80025', 'alt_color': '#231f20',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2641.png']},
         'Toledo': {'school': 'Toledo', 'mascot': 'Rockets', 'abbreviation': 'TOL', 'conference': 'Mid-American',
                    'division': 'West', 'color': '#00488F', 'alt_color': '#ffd51d',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2649.png']},
         'Troy': {'school': 'Troy', 'mascot': 'Trojans', 'abbreviation': 'TROY', 'conference': 'Sun Belt',
                  'division': None, 'color': '#AE0210', 'alt_color': '#88898c',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2653.png']},
         'Tulane': {'school': 'Tulane', 'mascot': 'Green Wave', 'abbreviation': 'TULN',
                    'conference': 'American Athletic', 'division': 'West', 'color': '#005837', 'alt_color': '#3baf29',
                    'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
                              'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2655.png']},
         'Tulsa': {'school': 'Tulsa', 'mascot': 'Golden Hurricane', 'abbreviation': 'TLSA',
                   'conference': 'American Athletic', 'division': 'West', 'color': '#004371', 'alt_color': '#ee3b33',
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/202.png']},
         'UAB': {'school': 'UAB', 'mascot': 'Blazers', 'abbreviation': 'UAB', 'conference': 'Conference USA',
                 'division': 'West', 'color': '#003b28', 'alt_color': '#ffc845',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/5.png']},
         'UCF': {'school': 'UCF', 'mascot': 'Knights', 'abbreviation': 'UCF', 'conference': 'American Athletic',
                 'division': 'East', 'color': '#000000', 'alt_color': '#231f20',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2116.png']},
         'UCLA': {'school': 'UCLA', 'mascot': 'Bruins', 'abbreviation': 'UCLA', 'conference': 'Pac-12',
                  'division': 'South', 'color': '#005C8E', 'alt_color': '#ffc72c',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png']},
         'UMass': {'school': 'UMass', 'mascot': 'Minutemen', 'abbreviation': 'UMASS', 'conference': 'FBS Independents',
                   'division': None, 'color': '#880007', 'alt_color': None,
                   'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
                             'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/113.png']},
         'UNLV': {'school': 'UNLV', 'mascot': 'Rebels', 'abbreviation': 'UNLV', 'conference': 'Mountain West',
                  'division': 'West', 'color': '#000000', 'alt_color': '#c2c4c6',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2439.png']},
         'USC': {'school': 'USC', 'mascot': 'Trojans', 'abbreviation': 'USC', 'conference': 'Pac-12',
                 'division': 'South', 'color': '#AE2531', 'alt_color': '#ffc72c',
                 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
                           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/30.png']},
         'Utah': {'school': 'Utah', 'mascot': 'Utes', 'abbreviation': 'UTAH', 'conference': 'Pac-12',
                  'division': 'South', 'color': '#890012', 'alt_color': '#7e8083',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/254.png']},
         'Utah State': {'school': 'Utah State', 'mascot': 'Aggies', 'abbreviation': 'USU',
                        'conference': 'Mountain West', 'division': 'Mountain', 'color': '#003263',
                        'alt_color': '#949ca1', 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
                                                          'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/328.png']},
         'UTEP': {'school': 'UTEP', 'mascot': 'Miners', 'abbreviation': 'UTEP', 'conference': 'Conference USA',
                  'division': 'West', 'color': '#002843', 'alt_color': '#ff6f12',
                  'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
                            'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2638.png']},
         'Vanderbilt': {'school': 'Vanderbilt', 'mascot': 'Commodores', 'abbreviation': 'VAN', 'conference': 'SEC',
                        'division': 'East', 'color': '#000000', 'alt_color': '#231f20',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/238.png']},
         'Virginia': {'school': 'Virginia', 'mascot': 'Cavaliers', 'abbreviation': 'UVA', 'conference': 'ACC',
                      'division': 'Coastal', 'color': '#00204e', 'alt_color': '#002d62',
                      'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
                                'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/258.png']},
         'Virginia Tech': {'school': 'Virginia Tech', 'mascot': 'Hokies', 'abbreviation': 'VT', 'conference': 'ACC',
                           'division': 'Coastal', 'color': '#74232D', 'alt_color': '#c2c1ba',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/259.png']},
         'Wake Forest': {'school': 'Wake Forest', 'mascot': 'Demon Deacons', 'abbreviation': 'WAKE',
                         'conference': 'ACC', 'division': 'Atlantic', 'color': '#9E7E38', 'alt_color': '#000000',
                         'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
                                   'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/154.png']},
         'Washington': {'school': 'Washington', 'mascot': 'Huskies', 'abbreviation': 'WASH', 'conference': 'Pac-12',
                        'division': 'North', 'color': '#2B2F64', 'alt_color': '#e8e3d3',
                        'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
                                  'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/264.png']},
         'West Virginia': {'school': 'West Virginia', 'mascot': 'Mountaineers', 'abbreviation': 'WVU',
                           'conference': 'Big 12', 'division': None, 'color': '#FFC600', 'alt_color': '#eaaa00',
                           'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
                                     'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/277.png']},
         'Wisconsin': {'school': 'Wisconsin', 'mascot': 'Badgers', 'abbreviation': 'WIS', 'conference': 'Big Ten',
                       'division': 'West', 'color': '#A00001', 'alt_color': '#f7f7f7',
                       'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
                                 'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/275.png']},
         'Wyoming': {'school': 'Wyoming', 'mascot': 'Cowboys', 'abbreviation': 'WYO', 'conference': 'Mountain West',
                     'division': 'Mountain', 'color': '#533B22', 'alt_color': '#ffffff',
                     'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
                               'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/2751.png']}}
